version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "api-gateway"
s3_bucket = "nested-sam-apps-example"
s3_prefix = "api-gateway"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
